### ISSUE TITLE
HotPepper APIからのデータのDB流し込み(5)

### ISSUE THREAD

**Issue by mab37** [RHD-Winter-Intern-teamF2016/app#26]
# Why

#5 のデータとして必要
担当: @jianghan0 

# What
- [x] tagsのデータを取得
- [x] genresのデータを取得
- [x] foodsのデータを取得
- [x] large_service_areasのデータを取得
- [x] large_areasのデータを取得
- [x] middle_areasのデータを取得
- [x] small_areasのデータを取得
- [x] shopsのデータを取得

**Comment by jianghan0** [comment]
データを入れ込むコマンド rake get_datas:all
