### ISSUE TITLE
DB設計 (5)

### ISSUE THREAD

**Issue by hytkgami** [RHD-Winter-Intern-teamF2016/app#5]
## WHY

#1 
使うデータをもとにデータベースを設計する。

## WHAT

- [x] カラムを考える
- [ ] マイグレーション

### テーブル一覧  
| テーブル名　| 説明 | 
|:--:|:--:|
|shops |店の詳細情報 | 
|tags | 店のタグ|
|genres|店のジャンル|
|users|　ユーザー情報|
|foods|　店の食べ物（特徴的な）|
|large_service_areas|　関東、東北とか|
|large_areas| 県|
|middle_areas|　区|
|small_areas|　区以下|
|||
|shop_tags | shopとtagの中間テーブル|
|shop_genres | shopとgenreの中間テーブル|
|shop_foods | shopとfoodの中間テーブル|
|histories| shopとuserの中間（ユーザーの利用履歴）|
|user_favorites| shopとユーザーの中間（お気に入り）|

### テーブル詳細  
**shops**  

| カラム　| 型 | 説明　| 例|
|:--:|:--:|:--:|:--:|
|id | integer |主キー | |
|shop_id |string |キー | J999999999 <br>主にこちらをキーとして使う|
|name |string |名前 | |
|name_kana |string |名前のかな | |
|logo_image |string |ロゴ画像 | |
|address |string |住所 | |
|large_service_area_code |string |関東、東北とか| |
|large_area |string |県| |
|middle_area |string |区| |
|small_area |string |区以下| |
|catch |string |キャッチフレーズ| | 
|capacity |integer |総席数 ||
|access |string |交通アクセス ||
|url_pc |string |PC向けURL ||
|url_mobile |string |携帯向けURL ||
|url_pc |string |PC向けURL ||
|url_mobile |string |携帯向けURL ||
|photo_pc |string |PC向け写真||
|photo_mobile |string |携帯向け写真||
|open |string |営業時間 ||
|close|string |定休日||
|card |string |カード支払い||
|non_smoking |string |禁煙席あるか||

***tags***  

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| name | string | タグ名 | | 
| value | float | タグの評価 |　中身未定<br>変更する可能性がある |

***genres***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| code | string | キー | G001  | 
| name | string | ジャンル名 | | 
| value | float | ジャンルの評価 |　中身未定<br>変更する可能性がある |

***users***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| name | string | 名前 | | 

***foods***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| code | string | キー | G001  | 
| name | string | 名前 | | 

***larege_service_areas***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| code | string | キー | G001  | 
| name | string | エリア | 東北、関東とか | 

***large_areas***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| code | string | キー | G001  | 
| name | string | 県 | 東京、千葉とか | 

***middle_areas***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| code | string | キー | G001  | 
| name | string | 区 | 新宿・銀座 | 

***small_areas***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| code | string | キー | G001  | 
| name | string | 区以下 | | 

#### 中間テーブル  
***shop_tags***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| shop_id | string | shopのID | | 
| tag_id | string | tagのID | | 

***shop_genres***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| shop_id | string | shopのID | | 
| genre_code | string | genresのコード | | 

***shop_foods***

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| shop_id | string | shopのID | | 
| food_id | string | foodのコード | | 

***histories***  

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| user_id | int | ユーザーID | |
| shop_id | string | 店ID | | 

***user_favorites***  

| カラム　| 型 | 説明　| 例 |
| :--: | :--: | :--: | :--: |
| id | int | 主キー | | 
| user_id | int | ユーザーID | |
| shop_id | string | 店ID | |

**Comment by jianghan0** [comment]
tags、genres、foods、larege_service_areas、large_areas等のテーブルにcodeカラムを追加

**Comment by jianghan0** [comment]
タグのcodeは使わないため、削除した
